

export enum Category {
  CAFE = 'Café',
  POSTRES = 'Postres',
  BEBIDAS = 'Bebidas',
  COMIDA = 'Comida',
  OTROS = 'Otros'
}

export interface Product {
  id: string;
  name: string;
  price: number;
  category: Category;
  image: string;
  color?: string;
  // New fields for Inventory Module
  sku?: string;
  stock?: number;
  status?: 'active' | 'draft' | 'archived';
}

export interface CartItem extends Product {
  quantity: number;
}

export interface Sale {
  id: string;
  date: Date;
  items: CartItem[];
  subtotal: number;
  tax: number;
  total: number;
  customerName?: string;
  clientId?: string; // Link to actual client
  paymentMethod: 'cash' | 'card' | 'transfer' | 'qr';
  aiMessage?: string; // Message generated by Gemini
}

export interface GeminiAnalysis {
  upsellSuggestion: string;
  thankYouNote: string;
}

export type UserRole = 'Superadmin' | 'Admin' | 'Cashier';

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  branches: string[];
  status: 'active' | 'inactive';
  avatar: string;
}

export interface Client {
  id: string;
  name: string;
  email?: string;
  phone?: string;
  taxId?: string; // DNI, RUT, CUIT
  address?: string;
  notes?: string;
}

export interface Branch {
  id: string;
  name: string;
  address: string;
  phone: string;
  email: string;
  status: 'active' | 'inactive';
  isMain?: boolean;
}